** info

Questo progetto nasce per ottenere un Emacs correttamente funzionante, configurabile e con interfaccia grafica, su un computer Windows 10 con pesanti limitazioni. 

Si deve cioe' poterlo installare: 

- senza usare la password di amministratore; 
- senza poter configurare variabili di sistema; 
- non potendo usare la Power Shell; 
- senza poter creare link simbolici (=mklink=); 
- senza la possibilita' di usare il sottosistema Linux per Windows (WSL);
- senza poter utilizzare /http proxy/ o l'accesso diretto ad Internet da Emacs.

La alternativa ragionevole e praticabile di installare Cygwin e utilizzare la versione di Emacs presente nella distribuzione e' stata scartata per ragioni di prestazioni e per la maggiore difficolta' di accedere al filesystem con path uguali a quelli di Windows.

Questa configurazione - non potendo far di meglio - prevede di collocare sul disco =C:= gli eseguibili di Emacs e sul disco =D:= i file di configurazione nella directory =d:\home=, dove sara' collocata anche la gran parte dei file di testo da /visitare/ con Emacs.

L'installazione, descritta piu' sotto, prevede soltanto di "unzippare" l'ultima versione di Emacs compilata per Windows (cfr. ) ed aggiungere poi i file di configurazione e i batch di avvio, presi in questo repository. Per la creazione delle directory corrette e' presente un batch di installazione, da lanciare una volta soltanto. 

Purtroppo, date le limitazioni di cui sopra - e per altre che per carita' di Patria e' opportuno tacere, alcuni passaggi manuali e a carico dell'utente sono ancora, al momento, richiesti.

/l.m./

** istruzioni
 
- Scaricare la versione per windows di Emacs (portable): =emacs-27.1-x86_64.zip= dal sito https://www.gnu.org/software/emacs/download.html [per esempio http://mirror.inode.at/gnu/emacs/windows/emacs-27/emacs-27.1-x86_64.zip].
- Scaricare questo repository in formato .zip, da qualche parte (p.es. =c:\tmp=).
- lanciare il batch =config-dir.bat=.
- Unzippare il file emacs-27.1-x86_64.zip in c:\emacs, facendogli creare la sottodirectory proposta (emacs-27.1-x86_64).
- copiare la directory '.emacs.d' del repository in d:\home
- copiare tutti i file batch "emacs*.bat" in c:\emacs\emacs-27.1-x86_64
- creare, almeno per emacs.bat uno shortcut di avvio sul desktop
- (modificare l'icona di questo shortcut utilizzando quella di emacs in c:\emacs\emacs-27.1-x86_64\share\icons\hicolor\scalable\apps\emacs.ico)
- (aggiugnere la variabile HOME=d:\home tra le variabili dell'utente)
- (inserire nell'avvio automatico di Windows il file batch "emacs--daemon.bat" per avere sempre attivo il server)
- (se si e' fatto il passo precedente: associare al file batch "emacsclient.bat" le estensioni dei file di testo che si vogliono editare con Emacs p.es. .txt, .org, .org etc.)

** grazie a 
- Jean-Philippe Theberge per =lorem-ipsum.el --- Insert dummy pseudo Latin text.=
- Bastien / @bzg2 / https://bzg.fr per An introduction to Emacs Lisp in 15 minutes (https://learnxinyminutes.com/docs/elisp/)
- Exedre
- Giupo
